from db import get_connection

def init_watchlist():
    conn = get_connection()
    cur = conn.cursor()
    
    print("🛠 Initializing Watchlist Table...")
    
    try:
        # Create Watchlist Table
        cur.execute("""
            DECLARE
                e_table_exists EXCEPTION;
                PRAGMA EXCEPTION_INIT(e_table_exists, -00955);
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE watchlist (
                        user_id NUMBER NOT NULL,
                        asteroid_id NUMBER NOT NULL,
                        added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT pk_watchlist PRIMARY KEY (user_id, asteroid_id),
                        CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                        CONSTRAINT fk_asteroid FOREIGN KEY (asteroid_id) REFERENCES asteroids(asteroid_id)
                    )
                ';
            EXCEPTION
                WHEN e_table_exists THEN
                    NULL;
            END;
        """)
        
        conn.commit()
        print("✅ Watchlist Table Ready.")

        # Create Messages Table
        print("🛠 Initializing Messages Table...")
        cur.execute("""
            DECLARE
                e_table_exists EXCEPTION;
                PRAGMA EXCEPTION_INIT(e_table_exists, -00955);
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE messages (
                        message_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        user_id NUMBER,
                        sender_name VARCHAR2(100),
                        message_text VARCHAR2(4000),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT pk_messages PRIMARY KEY (message_id)
                    )
                ';
            EXCEPTION
                WHEN e_table_exists THEN
                    NULL;
            END;
        """)
        conn.commit()
        print("✅ Messages Table Ready.")
        
    except Exception as e:
        print(f"❌ Error initializing DB: {e}")
    finally:
        cur.close()
        conn.close()

if __name__ == "__main__":
    init_watchlist()
